# apps on
# has to use awesome-client since the input steals keys
gesture swipe up 3 awesome-client "require('awful').screen.focused().launcher.visible = true"
gesture swipe down 3 awesome-client "require('awful').screen.focused().launcher.visible = false"

# next tag
gesture swipe left 3 _internal ws_left -w
# prev tag
gesture swipe right 3 _internal ws_right -w

# volume up
gesture swipe up 4 xdotool key XF86AudioRaiseVolume
# volume down
gesture swipe down 4 xdotool key XF86AudioLowerVolume

# browser forward
gesture swipe left xdotool key alt+Right
# browser back
gesture swipe right	xdotool key alt+Left

