// This code was autogenerated with `dbus-codegen-rust `, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgAwesomewmAkariconnect {
    fn empty(&self) -> Result<(), dbus::Error>;
    fn status(&self, status: &str) -> Result<(), dbus::Error>;
    fn position(&self, position: u64) -> Result<(), dbus::Error>;
    fn metadata(&self, title: &str, album: &str, artist: &str, length: u64, art: &str) -> Result<(), dbus::Error>;
}

#[derive(Debug)]
pub struct OrgAwesomewmAkariconnectPlayPause {
}

impl arg::AppendAll for OrgAwesomewmAkariconnectPlayPause {
    fn append(&self, _: &mut arg::IterAppend) {
    }
}

impl arg::ReadAll for OrgAwesomewmAkariconnectPlayPause {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgAwesomewmAkariconnectPlayPause {
        })
    }
}

impl dbus::message::SignalArgs for OrgAwesomewmAkariconnectPlayPause {
    const NAME: &'static str = "PlayPause";
    const INTERFACE: &'static str = "org.awesomewm.akariconnect";
}

#[derive(Debug)]
pub struct OrgAwesomewmAkariconnectNext {
}

impl arg::AppendAll for OrgAwesomewmAkariconnectNext {
    fn append(&self, _: &mut arg::IterAppend) {
    }
}

impl arg::ReadAll for OrgAwesomewmAkariconnectNext {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgAwesomewmAkariconnectNext {
        })
    }
}

impl dbus::message::SignalArgs for OrgAwesomewmAkariconnectNext {
    const NAME: &'static str = "Next";
    const INTERFACE: &'static str = "org.awesomewm.akariconnect";
}

#[derive(Debug)]
pub struct OrgAwesomewmAkariconnectPrevious {
}

impl arg::AppendAll for OrgAwesomewmAkariconnectPrevious {
    fn append(&self, _: &mut arg::IterAppend) {
    }
}

impl arg::ReadAll for OrgAwesomewmAkariconnectPrevious {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgAwesomewmAkariconnectPrevious {
        })
    }
}

impl dbus::message::SignalArgs for OrgAwesomewmAkariconnectPrevious {
    const NAME: &'static str = "Previous";
    const INTERFACE: &'static str = "org.awesomewm.akariconnect";
}

#[derive(Debug)]
pub struct OrgAwesomewmAkariconnectSeek {
    pub time: u64,
}

impl arg::AppendAll for OrgAwesomewmAkariconnectSeek {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.time, i);
    }
}

impl arg::ReadAll for OrgAwesomewmAkariconnectSeek {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgAwesomewmAkariconnectSeek {
            time: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgAwesomewmAkariconnectSeek {
    const NAME: &'static str = "Seek";
    const INTERFACE: &'static str = "org.awesomewm.akariconnect";
}

#[derive(Debug)]
pub struct OrgAwesomewmAkariconnectShift {
    pub by: i16,
}

impl arg::AppendAll for OrgAwesomewmAkariconnectShift {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.by, i);
    }
}

impl arg::ReadAll for OrgAwesomewmAkariconnectShift {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgAwesomewmAkariconnectShift {
            by: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgAwesomewmAkariconnectShift {
    const NAME: &'static str = "Shift";
    const INTERFACE: &'static str = "org.awesomewm.akariconnect";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgAwesomewmAkariconnect for blocking::Proxy<'a, C> {

    fn empty(&self) -> Result<(), dbus::Error> {
        self.method_call("org.awesomewm.akariconnect", "Empty", ())
    }

    fn status(&self, status: &str) -> Result<(), dbus::Error> {
        self.method_call("org.awesomewm.akariconnect", "Status", (status, ))
    }

    fn position(&self, position: u64) -> Result<(), dbus::Error> {
        self.method_call("org.awesomewm.akariconnect", "Position", (position, ))
    }

    fn metadata(&self, title: &str, album: &str, artist: &str, length: u64, art: &str) -> Result<(), dbus::Error> {
        self.method_call("org.awesomewm.akariconnect", "Metadata", (title, album, artist, length, art, ))
    }
}
