local bar = require("components.bar")
local control_center = require("components.control_center")
local dock = require("components.launcher.dock")
local launcher = require("components.launcher")
local desktop = require("components.desktop")
local execute = require("components.execute")
local media = require("components.media")
local osd = require("components.osd")

return function(s)
	bar(s)
	desktop(s)
	dock(s)
	media(s)
	launcher(s)
	control_center(s)
	execute(s)
	osd()
end
