#!/usr/bin/env python3
# @TODO get rid of this

from PIL import Image

colors = {
		'primary': (27, 8, 53),
		'secondary': (41, 25, 51),
		'accent': (70, 46, 41)
}

im = Image.open('base.png').convert('RGBA')
alpha = im.getchannel('A')
im = im.convert('RGB')

for name, rgb in colors.items():
	r, g, b = rgb

	matrix = (
		r / 100, 0, 0, 0,
		0, g / 100, 0, 0,
		0, 0, b / 100, 0
	)
	new = im.convert('RGB', matrix)
	
	new.putalpha(alpha)
	new.save(name + '.png')
