symbols: &symbols Symbols Nerd Font:pixelsize=12
azuki: &azuki azuki_font:pixelsize=20
love: &love b4637aff
gold: &gold b4637aff
bar:
  height: 42
  location: top
  font: *azuki
  layer: top
  foreground: 575279ff
  background: fffaf3aa

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 1
              default: {string: {text: ┻, font: *azuki}}
              conditions:
                state == urgent: {string: {text: u, font: *azuki, foreground: *gold}}
                state == focused: {string: {text: ┨, font: *azuki, foreground: *love}}
                id == 10: {string: {text: ┯, font: *azuki}}
        content:
          map:
            default:
              map:
                on-click:
                  left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
                  right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
                <<: *river_base
            conditions:
              state == invisible && ~occupied: {empty: {}}
