[general]
import = ["color.toml"]

[terminal.shell]
program = "hilbish"
args = ["-l", "-S"]

[env]
EDITOR = "nvim --listen ~/.cache/nvim/server.pipe"

[window]
padding = { x = 12, y = 12 }
dynamic_padding = true

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"
