[colors]
indexed_colors = [
	{ index = 229, color = "#C981BD" },
	{ index = 230, color = "#77A4D4"},
	{ index = 231, color = "#987BAD" },
]

[colors.primary]
foreground = "#E1E4F7"
background = "#14151C"
dim_foreground = "#ACA8BF"

[colors.selection]
text = "CellForeground"
background = "#232636"

[colors.normal]
black = "#232636"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#E1E4F7"

[colors.bright]
black = "#585663"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#E1E4F7"

[colors.dim]
black = "#585663"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#E1E4F7"